server.port: 8088
spring.thymeleaf.cache: false

server:
#?????session??????? ????Î»
  session-timeout: 1000
  tomcat:
    uri-encoding: UTF-8 #???UTF-8
    compression: on #tomcat???????? ???off
#  ssl:
##    key-store: classpath:.keystore
#    key-store: D:/.keystore
#    key-store-password: yf4821
#    key-store-type: JKS
#    key-alias: tomcat
#?????static ??springboot ?????????favicon.ico
spring:
  mvc:
    favicon:
      enabled: true #?????